from __future__ import annotations
from typing import Any, Protocol
import numpy as np


class RobotIO(Protocol):
    def observe(self) -> dict[str, Any]: ...
    def state_action16(self) -> np.ndarray: ...
    def command_target16(self) -> np.ndarray: ...
    def execute(self, action16: np.ndarray) -> None: ...
    def execute_absolute(self, action16: np.ndarray) -> None: ...
    def reset_history(self, action16: np.ndarray) -> None: ...


class Policy(Protocol):
    def reset(self, observation: dict[str, Any] | None) -> None: ...
    def infer(self, observation: dict[str, Any]) -> np.ndarray: ...
